#!/bin/bash
  conky -c ~/.conky/network.conkyrc &
  conky -c ~/.conky/weather.conkyrc &
  conky -c ~/.conky/logs.conkyrc & exit;

  #conky -c ~/.conky/info.conkyrc &
  #conky -c ~/.conky/sys.conkyrc & exit;

#conky -c ~/.conky/.conkyrc_sysproc &
#conky -c ~/.conky/.conkyrc_cal_email #&
#conky -c ~/.conky/.conkyrc_weather

# #!/bin/bash
# if ps aux | grep -vE 'grep|bash' | grep conky >/dev/null;then
#     echo 'exit';
# else
#     sleep 5
#     conky -c ~/.conky/network.conkyrc &
#     conky -c ~/.conky/weather.conkyrc &
#     conky -c ~/.conky/logs.conkyrc & exit;

#     #conky -c ~/.conky/info.conkyrc &
#     #conky -c ~/.conky/sys.conkyrc & exit;
# fi
